ktor:
    application:
        modules:
            - com.globalbaholash.ApplicationKt.module
    deployment:
        port: 8080
        watch: [ classes, resources ]
jwt:
  secret: "alisher-nozima-xumoyun-maxfuza-xondamir"
  issuer: "http://localhost:8080"
  audience: "assessment-app-users"
  realm: "AssessmentAppRealm"
  expirationTimeMs: 3600000

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/assessment_app_db"
  driverClassName: "org.postgresql.Driver"
  username: "khondamiri"
  password: "khondamiri"
  maxPoolSize: 3
  autoCommit: false
  transactionIsolation: "TRANSACTION_REPEATABLE_READ"

email:
  smtpHost: "smtp.gmail.com"
  smtpPort: 587
  smtpUsername: "globalbaholash1@gmail.com"
  smtpPassword: "dbcwuqzjwgxsnqvk"
  fromAddress: "globalbaholash1@gmail.com"
  fromName: "Global Baholash"
  enableTls: true
  enableSsl: false

server:
  baseUrl: "http://localhost:8080"